### ISSUE TITLE
Error when updated to 6.0.1

### ISSUE THREAD

**Issue by noeGnh** [iamstevendao/vue-tel-input#363]
I have this error in my console after update to version 6.0.1
```
app.js:2648 Uncaught ReferenceError: Vue is not defined
    at eval (vue-tel-input.iife.js?0b9f:11:1)
    at ./node_modules/vue-tel-input/dist/vue-tel-input.iife.js (chunk-vendors.js:8767:1)
    at __webpack_require__ (app.js:2645:33)
    at fn (app.js:2963:21)
    at eval (main.js:22:72)
    at ./src/main.js (app.js:42:1)
    at __webpack_require__ (app.js:2645:33)
    at app.js:3888:109
    at __webpack_require__.O (app.js:2699:23)
    at app.js:3889:53
```

**Comment by iamumangsuthar** [comment]
Facing similar issue with Vue-3 after upgrading to version 6.0.1 from beta version.

**Comment by aaflatooni** [comment]
We are experiencing the same issue as well.

**Comment by iamstevendao** [comment]
hey guys, i have just published the potential fix https://github.com/iamstevendao/vue-tel-input/commit/66c4ea67c4d380567695cf90b0c0a47f9536d7b3. can you try `v6.0.3`?
feel free to re-open if it persists.
